### ISSUE TITLE
error installing amico 

### ISSUE THREAD

**Issue by rosella1234** [daducci/AMICO#118]
I have successfully installed AMICO with `pip install dmri-amico`
However, when importing it in python, the following error occurs:

```
(base) [rosella@beatrix ~]$ python
Python 3.8.8 (default, Apr 13 2021, 19:58:26)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import amico
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rosella/anaconda3/lib/python3.8/site-packages/amico/__init__.py", line 3, in <module>
    from .core import Evaluation
  File "/home/rosella/anaconda3/lib/python3.8/site-packages/amico/core.py", line 15, in <module>
    import amico.models
  File "/home/rosella/anaconda3/lib/python3.8/site-packages/amico/models.py", line 25, in <module>
    import spams
  File "/home/rosella/anaconda3/lib/python3.8/site-packages/spams/__init__.py", line 6, in <module>
    from .spams import *
  File "/home/rosella/anaconda3/lib/python3.8/site-packages/spams/spams.py", line 9, in <module>
    import spams_wrap
  File "/home/rosella/anaconda3/lib/python3.8/site-packages/spams_wrap/__init__.py", line 6, in <module>
    from .spams_wrap import *
  File "/home/rosella/anaconda3/lib/python3.8/site-packages/spams_wrap/spams_wrap.py", line 193, in <module>
    _spams_wrap.L1COEFFS_swigconstant(_spams_wrap)
AttributeError: module '_spams_wrap' has no attribute 'L1COEFFS_swigconstant'
```
My OS feature are:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

 thank you

**Comment by daducci** [comment]
Hi Rosella,

it seems like a problem with SPAMS, probably its installation failed. Did you notice any error about this in the log during the istallation?

**Comment by rosella1234** [comment]
Hi. Thank you. I think SPAMS installation worked successfully. No error appeared. 
Rosella

**Comment by MarioOcampo** [comment]
Hello @rosella1234, 

in the case of anaconda sometimes other SPAMS versions work. Could you try [this proposal](https://github.com/daducci/AMICO/issues/61#issuecomment-383037278)? 

Let us know if this works.
Best 
Mario

**Comment by rosella1234** [comment]
Hi
I think this worked.
thank you very much! 
Rosella
