### ISSUE TITLE
Error when interrupting AMICO

### ISSUE THREAD

**Issue by saraponti** [daducci/AMICO#122]
Hi,
I run AMICO to estimate a NODDI model on python 3.6.9 on linux, but I accidentally interrupted it during the fitting (ae.fit()). Now when I try to re-run (in python 3.6.9), the process interrupts with the error reported below. 
With another python version (2.7.17) it seems to work correctly. Con you suggest a way to fix this issue?
Thanks,

Sara

joblib.externals.loky.process_executor._RemoteTraceback:                                         |  0.0%
"""
Traceback (most recent call last):
  File "/home/sara/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/sara/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/sara/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/sara/.local/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/sara/.local/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/sara/.local/lib/python3.6/site-packages/amico/core.py", line 365, in fit_voxel
    results, dirs, x, A = self.model.fit( y, dirs, self.KERNELS, self.get_config('solver_params'), self.htable)
  File "/home/sara/.local/lib/python3.6/site-packages/amico/models.py", line 662, in fit
    x, _ = scipy.optimize.nnls( A, y )
TypeError: Required argument 'n' (pos 3) not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sara/.local/lib/python3.6/site-packages/amico/core.py", line 457, in fit
    for i in tqdm(range(totVoxels), ncols=70, bar_format='   |{bar}| {percentage:4.1f}%')
  File "/home/sara/.local/lib/python3.6/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/sara/.local/lib/python3.6/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/sara/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: Required argument 'n' (pos 3) not found

**Comment by daducci** [comment]
Ciao Sara,

that's a weird problem, indeed (in fact, it should not work at all with python2...). First of all, does it still happen also if you close the terminal and re-open a new python/ipython session? Besides, did you have a look at the following issue #107 ? It looks you're getting the very same error.

**Comment by saraponti** [comment]
Thanks for the very quick reply!
Following issue #107 I reinstalled scipy in the exact same version I had before (version 1.5.4), and I don't know why but it works now. Actually I think it was a problem related to the parallel processing since the first test I did (the one I accidentally interrupted) reached 65% of the total time processing after ~2h (on a 16Gb RAM) while now the fitting lasted ~2 minutes.
Thanks again,

Sara

**Comment by daducci** [comment]
I'm glad it works now! Please let us know if this happens again. It is not directly related to AMICO per se, but apparently there's a library which (sometimes) create problems, and it'd be nice to figure it out in which conditions this happens. Thanks!
