### ISSUE TITLE
Issue running subjects after first response.

### ISSUE THREAD

**Issue by CallowBrainProject** [daducci/AMICO#94]
Hello, I was able to run amico fully through for my first subject using the following commands...

```
#!/bin/tcsh
#SBATCH --time=300:00:00
#SBATCH --mem=60000
#SBATCH --output=result
#SBATCH --cores=4

set echo
set subj= ($argv[1]) \

cd /data/bswift-1/dcallow/CONNECTOME/dwi/${subj}/T1w/Diffusion
rm -R -f /data/bswift-1/dcallow/CONNECTOME/dwi/${subj}/T1w/Diffusion/bvals.scheme
source /data/bswift-0/software/loadpython3.csh 3.7

python <<EOF
import amico
import spams
#import camino
amico.core.setup()

ae = amico.Evaluation("/data/bswift-1/dcallow/CONNECTOME/dwi/", "${subj}/T1w/Diffusion")
amico.util.fsl2scheme("/data/bswift-1/dcallow/CONNECTOME/dwi/${subj}/T1w/Diffusion/bvals","/data/bswift-1/dcallow/CONNE$ae.load_data(dwi_filename = "data.nii.gz", scheme_filename = "bvals.scheme", mask_filename ="nodif_brain_mask.nii.gz", $ae.set_model("NODDI")
ae.generate_kernels()
ae.load_kernels()
ae.fit()
ae.save_results()

EOF
```
###### Output#####
```
-> Preprocessing:
        * Normalizing to b0... [ min=0.00,  mean=0.18, max=6179.81 ]
        * Keeping all b0 volume(s)...
   [ 30.1 seconds ]

-> Creating LUT for "NODDI" model:
   [ LUT already computed. Call "generate_kernels( regenerate=True )" to force regeneration. ]

-> Resampling LUT for subject "100408/T1w/Diffusion":
Traceback (most recent call last):
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/lut.py", line 305, in res$
    KR[i,idx_out] = np.dot( Ylm_out, KRlm[i,:] ).astype(np.float32)
ValueError: shapes (270,1547) and (1638,) not aligned: 1547 (dim 1) != 1638 (dim 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/core.py", line 287, in lo$
    self.KERNELS = self.model.resample( self.get_config('ATOMS_path'), idx_OUT, Ylm_OUT, self.get_config('doMergeB0'), self.get_con$
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/models.py", line 574, in $
    KERNELS['wm'][idx,:,:] = amico.lut.resample_kernel( lm, self.scheme.nS, idx_out, Ylm_out, False, ndirs )[:,merge_idx]
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/lut.py", line 307, in res$
    raise RuntimeError( '[ Outdated LUT. Call "generate_kernels( regenerate=True )" to update the LUT. ]' )
RuntimeError: [ Outdated LUT. Call "generate_kernels( regenerate=True )" to update the LUT. ]
```

I am running this on Human Connectome Project Data and have run into this error after successfully running on subject #1. Does anyone have any suggestions for why this issue keeps occurring?

**Comment by CallowBrainProject** [comment]
Something to note is I am trying to run this on HCP data and therefore the bval schemes are slightly different (off by a bval of +/-5 or so) for each subject because of the scanner they use.

**Comment by MarioOcampo** [comment]
Hello @CallowBrainProject, 
thanks for using AMICO and sending us your question. 

What version of AMICO are you using? If you recently updated AMICO, you probably need to regenerate the kernels if these were generated with a previous version. 
Try the command `generate_kernels (regenerate = True)` to force the recreation of the kernels.  

To handle the b-value differences you can use the option `bStep` in the function `amico.util.fsl2scheme` and the parameter `b0_thr` in the function `ae.load_data`. 

Best

**Comment by CallowBrainProject** [comment]
Hello and thank you for the response! I have not changed versions of AMICO and just recently downloaded the software! 

I am running AMICO on a cluster and thus trying to model multiple subjects at once. Could this be an issue when computing the kernel? So far when I compute the kernel it creates it in one folder. Although if I recalculate it each time I think it will keep interupting the computation in the original /kernel/NODDI folder. The real issue appears to occur when trying to resample the Lut to the subject. 

As I said before I think maybe it is because of the slightly different bvals? I have already edited b0_thr =5 so the b0 is fine. The main issue I think is that the difference between 995 and 1005 or so between subjects scans. It sounds like bStep might be able to help with this (if the bval scheme is slightly different between subjects despite them all being part of the same protocol)?

To try this solution how would I add/implement bStep to my script?

specifically, this is where the error is occurring for all subjects...

```
-> Resampling LUT for subject "100408/T1w/Diffusion":
Traceback (most recent call last):
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/lut.py", line 305, in res$
    KR[i,idx_out] = np.dot( Ylm_out, KRlm[i,:] ).astype(np.float32)
ValueError: shapes (270,1547) and (1638,) not aligned: 1547 (dim 1) != 1638 (dim 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/core.py", line 287, in lo$
    self.KERNELS = self.model.resample( self.get_config('ATOMS_path'), idx_OUT, Ylm_OUT, self.get_config('doMergeB0'), self.get_con$
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/models.py", line 574, in $
    KERNELS['wm'][idx,:,:] = amico.lut.resample_kernel( lm, self.scheme.nS, idx_out, Ylm_out, False, ndirs )[:,merge_idx]
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/lut.py", line 307, in res$
    raise RuntimeError( '[ Outdated LUT. Call "generate_kernels( regenerate=True )" to update the LUT. ]' )
RuntimeError: [ Outdated LUT. Call "generate_kernels( regenerate=True )" to update the LUT. ]
```

**Comment by CallowBrainProject** [comment]
Thank you for the response!

So I am running things on a cluster (trying to compute for multiple subjects at once) so I think regenerating might be a problem (especially if trying to regenerate for multiple subjects at once).

I also haven't changed AMICO since downloading (which I only downloaded recently - a few days ago - so AMICO should be recent).

Since I am getting this issue specifically...

```
-> Resampling LUT for subject "100408/T1w/Diffusion":
Traceback (most recent call last):
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/lut.py", line 305, in res$
    KR[i,idx_out] = np.dot( Ylm_out, KRlm[i,:] ).astype(np.float32)
ValueError: shapes (270,1547) and (1638,) not aligned: 1547 (dim 1) != 1638 (dim 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/core.py", line 287, in lo$
    self.KERNELS = self.model.resample( self.get_config('ATOMS_path'), idx_OUT, Ylm_OUT, self.get_config('doMergeB0'), self.get_con$
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/models.py", line 574, in $
    KERNELS['wm'][idx,:,:] = amico.lut.resample_kernel( lm, self.scheme.nS, idx_out, Ylm_out, False, ndirs )[:,merge_idx]
  File "/a/ha-nfs-1-ib/export/data/bswift-0/software/python3-addons/3.7/lib/python3.7/site-packages/amico/lut.py", line 307, in res$
    raise RuntimeError( '[ Outdated LUT. Call "generate_kernels( regenerate=True )" to update the LUT. ]' )
RuntimeError: [ Outdated LUT. Call "generate_kernels( regenerate=True )" to update the LUT. ]
'''

I will try the bStep technique as I think that maybe the problem and why resampling isn't working?

**Comment by MarioOcampo** [comment]
Hello @CallowBrainProject , 
yes the problem is that the protocols are different, and dictionaries are not compatible.
You can try `amico.util.fsl2scheme(bvals,bvecs, bStep = 1000.0)` to create a scheme file that creates kernels that can be used for different subjects.

**Comment by CallowBrainProject** [comment]
Thank you! That solved the issue!
